easy_admin:
    site_name: 'Aqua<i>Note</i>'
    design:
        brand_color: '#81b9ba'
        assets:
            css: ['css/custom_backend.css']
            js:
                - 'https://unpkg.com/snarkdown@1.2.2/dist/snarkdown.umd.js'
                - 'js/custom_backend.js'
        templates:
            field_id: 'admin/fields/_id.html.twig'
        form_theme:
            - horizontal
            - easy_admin/_form_theme.html.twig
        menu:
            - { label: 'Dashboard', route: 'admin_dashboard', default: true }
            - { label: 'Open front-end', route: 'app_genus_list' }
            - { entity: 'User', label: 'Users', icon: 'user' }
            -
                label: 'Genus'
                children:
                    - Genus
                    -
                        entity: 'Genus'
                        label: 'Genuses (sorted by ID)'
                        params:
                            sortField: 'id'
                            sortDirection: 'ASC'
                            pizza: 'delicious'
                    -
                        entity: 'Genus'
                        label: 'Pet genus'
                        icon: 'paw'
                        params:
                            action: 'show'
                            id: 2
                    - GenusHorde
            - { label: 'Related' }
            - { entity: 'GenusNote', label: 'Notes', icon: 'sticky-note' }
            - { entity: 'SubFamily', label: 'Sub-Families', icon: '' }
            -
                label: 'Important stuff'
                icon: 'exclamation'
                children:
                    -
                        label: 'Silly kittens'
                        url: 'https://www.youtube.com/results?search_query=silly+kittens'
                        target: '_blank'
                    -
                        label: 'Wet cats'
                        url: 'http://www.boredpanda.com/funny-wet-cats/'
                        target: '_blank'
    list:
        title: 'List of %%entity_label%%'
        actions: ['show', 'export']
    entities:
        Genus:
            class: AppBundle\Entity\Genus
            controller: AppBundle\Controller\EasyAdmin\GenusController
            label: Genuses
            help: Genuses are not covered under warranty!
            list:
                help: Do not feed!
                actions:
                    - { name: 'edit', icon: 'pencil', label: 'Edit' }
                    - { name: 'show', icon: 'info-circle', label: '' }
                fields:
                    - 'id'
                    - 'name'
                    - 'isPublished'
                    - { property: 'firstDiscoveredAt', format: 'M Y', label: 'Discovered' }
                    - 'funFact'
                    - { property: 'speciesCount', format: '%b' }
                sort: 'name'
            search:
                help: null
                fields: ['id', 'name']
            show:
                actions:
                    -
                        name: 'genus_feed'
                        type: 'route'
                        label: 'Feed genus'
                        css_class: 'btn btn-info'
                        icon: 'cutlery'
                    - { name: 'changePublishedStatus', css_class: 'btn' }
#            templates:
#                field_id: 'admin/fields/_id.html.twig'
            form:
                fields:
                    - { type: 'group', css_class: 'col-sm-6', label: 'Basic information' }
                    - name
                    - speciesCount
                    - { property: 'firstDiscoveredAt', type_options: { widget: 'single_text' }}
                    - { property: 'subFamily', type: 'easyadmin_autocomplete' }
                    - { type: 'section', label: 'Optional' }
                    - { property: 'funFact', type: 'textarea', css_class: 'js-markdown-input' }
                    - isPublished
                    - { type: 'group', css_class: 'col-sm-6', label: 'Studied by ...' }
                    -
                        property: 'genusScientists'
                        type: 'text'
                        type_options:
                            mapped: false
                            attr: { class: 'js-genus-scientists-field' }
                    -
                        type: 'group'
                        css_class: 'col-sm-6 new-row'
                        label: 'Identification'
                        icon: 'id-card-o'
                        help: 'For administrators'
                    -
                        property: id
                        type_options: { disabled: true }

                    -
                        property: 'slug'
                        help: 'unique auto-generated value'
                        type_options: { disabled: true }
            new:
                fields:
                    - '-id'
                    - '-slug'

        GenusHorde:
            class: AppBundle\Entity\Genus
            label: HORDE of Genuses 😱 !!!
            list:
                dql_filter: 'entity.speciesCount >= 50000 AND entity.isPublished = true'
                sort: 'speciesCount'
                help: Run for your life!!! 😱😱😱
            search:
                dql_filter: 'entity.speciesCount >= 50000'
        GenusNote:
            class: AppBundle\Entity\GenusNote
            label: Genus Notes
            list:
                title: List of notes
                fields:
                    - id
                    - username
                    - { property: 'userAvatarFilename', label: 'User avatar', type: 'image', base_path: '/images/', sortable: false }
                    - createdAt
                    - genus
                sort: ['genus.name', 'ASC']
        SubFamily:
            class: AppBundle\Entity\SubFamily
            list:
                actions: ['-show']
            disabled_actions: ['show']
        User:
            class: AppBundle\Entity\User
            controller: AppBundle\Controller\EasyAdmin\UserController
            list:
                fields:
                    - id
                    - { property: 'email', type: 'email' }
                    - { property: 'isScientist', label: 'Is scientist?', type: 'boolean' }
                    - { property: 'fullName', template: '_field_user_full_name.html.twig' }
                    - { property: 'avatarUri', type: 'url' }
            form:
                fields:
                    - { type: 'section', label: 'User details' }
                    - { property: 'fullName', type: 'text', help: 'First then Last' }
                    - { type: 'divider' }
                    - avatarUri
                    -
                        type: 'section'
                        label: 'Contact information'
                        icon: 'phone'
                        help: 'Only for emergencies!'
                        css_class: 'any-you-want'
                    - email
                    - { type: 'section', label: 'Education' }
                    - isScientist
                    - universityName
